CREATE EXTENSION IF NOT EXISTS postgis;
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911141415_InitialSchemaAndPostGis') THEN
    CREATE EXTENSION IF NOT EXISTS postgis;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911141415_InitialSchemaAndPostGis') THEN
    CREATE TABLE "AdministrativeUnits" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Code" character varying(20) NOT NULL,
        "Name" character varying(150) NOT NULL,
        "EnglishName" character varying(150),
        "Level" integer NOT NULL,
        "ParentId" integer,
        CONSTRAINT "PK_AdministrativeUnits" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AdministrativeUnits_AdministrativeUnits_ParentId" FOREIGN KEY ("ParentId") REFERENCES "AdministrativeUnits" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911141415_InitialSchemaAndPostGis') THEN
    CREATE TABLE "PetitionCategories" (
        "Id" uuid NOT NULL,
        "Name" character varying(200) NOT NULL,
        "Code" character varying(50) NOT NULL,
        "CategoryType" integer NOT NULL,
        "Description" text,
        "DefaultSlaHours" integer NOT NULL,
        "DisplayOrder" integer NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedBy" text,
        "LastModifiedBy" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_PetitionCategories" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911141415_InitialSchemaAndPostGis') THEN
    CREATE TABLE "Departments" (
        "Id" uuid NOT NULL,
        "Name" character varying(250) NOT NULL,
        "Code" character varying(50) NOT NULL,
        "Description" text,
        "Phone" character varying(20),
        "Email" character varying(100),
        "Address" character varying(300),
        "IsActive" boolean NOT NULL,
        "AdministrativeUnitId" integer,
        "CreatedBy" text,
        "LastModifiedBy" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_Departments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Departments_AdministrativeUnits_AdministrativeUnitId" FOREIGN KEY ("AdministrativeUnitId") REFERENCES "AdministrativeUnits" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911141415_InitialSchemaAndPostGis') THEN
    CREATE TABLE "Users" (
        "Id" uuid NOT NULL,
        "Username" character varying(50) NOT NULL,
        "FullName" character varying(150) NOT NULL,
        "Email" character varying(100) NOT NULL,
        "PhoneNumber" character varying(20),
        "PasswordHash" text NOT NULL,
        "PasswordSalt" text NOT NULL,
        "Role" integer NOT NULL,
        "IsActive" boolean NOT NULL,
        "LastLoginAt" timestamp with time zone,
        "RefreshToken" text,
        "RefreshTokenExpiryTime" timestamp with time zone,
        "DepartmentId" uuid,
        "CreatedBy" text,
        "LastModifiedBy" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Users_Departments_DepartmentId" FOREIGN KEY ("DepartmentId") REFERENCES "Departments" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911141415_InitialSchemaAndPostGis') THEN
    CREATE TABLE "Petitions" (
        "Id" uuid NOT NULL,
        "TrackingCode" character varying(30) NOT NULL,
        "Title" character varying(300) NOT NULL,
        "Content" text NOT NULL,
        "LocationGeometry" geometry(Point, 4326),
        "Latitude" double precision,
        "Longitude" double precision,
        "AddressText" character varying(500) NOT NULL,
        "AdministrativeUnitId" integer,
        "IsAnonymous" boolean NOT NULL,
        "CitizenName" character varying(150),
        "CitizenPhone" character varying(20),
        "CitizenEmail" character varying(100),
        "CitizenIdCard" character varying(25),
        "Status" integer NOT NULL,
        "PriorityLevel" integer NOT NULL,
        "CategoryId" uuid NOT NULL,
        "DepartmentId" uuid,
        "AssignedUserId" uuid,
        "DueDate" timestamp with time zone,
        "ResolvedAt" timestamp with time zone,
        "ResolutionSummary" text,
        "CreatedBy" text,
        "LastModifiedBy" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_Petitions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Petitions_AdministrativeUnits_AdministrativeUnitId" FOREIGN KEY ("AdministrativeUnitId") REFERENCES "AdministrativeUnits" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_Petitions_Departments_DepartmentId" FOREIGN KEY ("DepartmentId") REFERENCES "Departments" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_Petitions_PetitionCategories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "PetitionCategories" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Petitions_Users_AssignedUserId" FOREIGN KEY ("AssignedUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911141415_InitialSchemaAndPostGis') THEN
    CREATE TABLE "CitizenFeedbacks" (
        "Id" uuid NOT NULL,
        "PetitionId" uuid NOT NULL,
        "Rating" integer NOT NULL,
        "Comment" character varying(1000),
        "FeedbackAt" timestamp with time zone NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_CitizenFeedbacks" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CitizenFeedbacks_Petitions_PetitionId" FOREIGN KEY ("PetitionId") REFERENCES "Petitions" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911141415_InitialSchemaAndPostGis') THEN
    CREATE TABLE "PetitionAttachments" (
        "Id" uuid NOT NULL,
        "PetitionId" uuid NOT NULL,
        "FileName" character varying(255) NOT NULL,
        "OriginalFileName" character varying(255) NOT NULL,
        "FileUrl" text NOT NULL,
        "FileType" integer NOT NULL,
        "MimeType" character varying(100) NOT NULL,
        "FileSize" bigint NOT NULL,
        "ThumbnailUrl" text,
        "ExifLatitude" double precision,
        "ExifLongitude" double precision,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_PetitionAttachments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PetitionAttachments_Petitions_PetitionId" FOREIGN KEY ("PetitionId") REFERENCES "Petitions" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911141415_InitialSchemaAndPostGis') THEN
    CREATE TABLE "PetitionComments" (
        "Id" uuid NOT NULL,
        "PetitionId" uuid NOT NULL,
        "AuthorName" character varying(150) NOT NULL,
        "AuthorUserId" uuid,
        "IsInternal" boolean NOT NULL,
        "Content" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_PetitionComments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PetitionComments_Petitions_PetitionId" FOREIGN KEY ("PetitionId") REFERENCES "Petitions" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_PetitionComments_Users_AuthorUserId" FOREIGN KEY ("AuthorUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911141415_InitialSchemaAndPostGis') THEN
    CREATE TABLE "PetitionHistories" (
        "Id" uuid NOT NULL,
        "PetitionId" uuid NOT NULL,
        "FromStatus" integer,
        "ToStatus" integer NOT NULL,
        "Action" character varying(150) NOT NULL,
        "Note" text,
        "PerformedByUserId" uuid,
        "PerformedByName" character varying(150),
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_PetitionHistories" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PetitionHistories_Petitions_PetitionId" FOREIGN KEY ("PetitionId") REFERENCES "Petitions" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_PetitionHistories_Users_PerformedByUserId" FOREIGN KEY ("PerformedByUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911141415_InitialSchemaAndPostGis') THEN
    CREATE TABLE "PetitionResolutions" (
        "Id" uuid NOT NULL,
        "PetitionId" uuid NOT NULL,
        "ConclusionText" text NOT NULL,
        "DocumentNumber" character varying(100),
        "OfficialDocumentUrl" text,
        "ApprovedByUserId" uuid,
        "IssuedAt" timestamp with time zone NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_PetitionResolutions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PetitionResolutions_Petitions_PetitionId" FOREIGN KEY ("PetitionId") REFERENCES "Petitions" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_PetitionResolutions_Users_ApprovedByUserId" FOREIGN KEY ("ApprovedByUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911141415_InitialSchemaAndPostGis') THEN
    CREATE UNIQUE INDEX "IX_AdministrativeUnits_Code" ON "AdministrativeUnits" ("Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911141415_InitialSchemaAndPostGis') THEN
    CREATE INDEX "IX_AdministrativeUnits_ParentId" ON "AdministrativeUnits" ("ParentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911141415_InitialSchemaAndPostGis') THEN
    CREATE UNIQUE INDEX "IX_CitizenFeedbacks_PetitionId" ON "CitizenFeedbacks" ("PetitionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911141415_InitialSchemaAndPostGis') THEN
    CREATE INDEX "IX_Departments_AdministrativeUnitId" ON "Departments" ("AdministrativeUnitId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911141415_InitialSchemaAndPostGis') THEN
    CREATE UNIQUE INDEX "IX_Departments_Code" ON "Departments" ("Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911141415_InitialSchemaAndPostGis') THEN
    CREATE INDEX "IX_PetitionAttachments_PetitionId" ON "PetitionAttachments" ("PetitionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911141415_InitialSchemaAndPostGis') THEN
    CREATE UNIQUE INDEX "IX_PetitionCategories_Code" ON "PetitionCategories" ("Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911141415_InitialSchemaAndPostGis') THEN
    CREATE INDEX "IX_PetitionComments_AuthorUserId" ON "PetitionComments" ("AuthorUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911141415_InitialSchemaAndPostGis') THEN
    CREATE INDEX "IX_PetitionComments_PetitionId" ON "PetitionComments" ("PetitionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911141415_InitialSchemaAndPostGis') THEN
    CREATE INDEX "IX_PetitionHistories_PerformedByUserId" ON "PetitionHistories" ("PerformedByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911141415_InitialSchemaAndPostGis') THEN
    CREATE INDEX "IX_PetitionHistories_PetitionId" ON "PetitionHistories" ("PetitionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911141415_InitialSchemaAndPostGis') THEN
    CREATE INDEX "IX_PetitionResolutions_ApprovedByUserId" ON "PetitionResolutions" ("ApprovedByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911141415_InitialSchemaAndPostGis') THEN
    CREATE UNIQUE INDEX "IX_PetitionResolutions_PetitionId" ON "PetitionResolutions" ("PetitionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911141415_InitialSchemaAndPostGis') THEN
    CREATE INDEX "IX_Petitions_AdministrativeUnitId" ON "Petitions" ("AdministrativeUnitId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911141415_InitialSchemaAndPostGis') THEN
    CREATE INDEX "IX_Petitions_AssignedUserId" ON "Petitions" ("AssignedUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911141415_InitialSchemaAndPostGis') THEN
    CREATE INDEX "IX_Petitions_CategoryId" ON "Petitions" ("CategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911141415_InitialSchemaAndPostGis') THEN
    CREATE INDEX "IX_Petitions_CreatedAt" ON "Petitions" ("CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911141415_InitialSchemaAndPostGis') THEN
    CREATE INDEX "IX_Petitions_DepartmentId" ON "Petitions" ("DepartmentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911141415_InitialSchemaAndPostGis') THEN
    CREATE INDEX "IX_Petitions_LocationGeometry" ON "Petitions" USING GIST ("LocationGeometry");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911141415_InitialSchemaAndPostGis') THEN
    CREATE INDEX "IX_Petitions_PriorityLevel" ON "Petitions" ("PriorityLevel");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911141415_InitialSchemaAndPostGis') THEN
    CREATE INDEX "IX_Petitions_Status" ON "Petitions" ("Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911141415_InitialSchemaAndPostGis') THEN
    CREATE UNIQUE INDEX "IX_Petitions_TrackingCode" ON "Petitions" ("TrackingCode");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911141415_InitialSchemaAndPostGis') THEN
    CREATE INDEX "IX_Users_DepartmentId" ON "Users" ("DepartmentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911141415_InitialSchemaAndPostGis') THEN
    CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911141415_InitialSchemaAndPostGis') THEN
    CREATE UNIQUE INDEX "IX_Users_Username" ON "Users" ("Username");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260911141415_InitialSchemaAndPostGis') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260911141415_InitialSchemaAndPostGis', '9.0.20');
    END IF;
END $EF$;
COMMIT;

